"""empty message

Revision ID: 1b71b5287805
Revises: 60c08b9bae01
Create Date: 2025-09-30 19:40:24.037650

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b71b5287805'
down_revision = '60c08b9bae01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('sid', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type_aircraft', sa.String(length=128), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('reg_departure', sa.String(length=128), nullable=True),
    sa.Column('departure_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('departure_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('reg_arrival', sa.String(length=128), nullable=True),
    sa.Column('arrival_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('arrival_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk__flights'))
    )
    op.create_unique_constraint(op.f('uq__user__id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user__id'), 'user', type_='unique')
    op.drop_table('flights')
    # ### end Alembic commands ###
